### ISSUE TITLE
[Feature Request] Enable emojis

### ISSUE THREAD

**Issue by jahway603** [FossifyOrg/SMS-Messenger#17]
**Checklist**
 - [X] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [X]  I have read the FAQ and my problem isn't listed.
 - [X]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [X]  This issue contains only one feature request.
 - [X]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
Unable to send emoji in text messages as they are just not available for my use in this app.

**Describe the solution you'd like**
I would like to be able to use emojis in my text messages.

**Describe alternatives you've considered**
I can copy and paste emojis from other apps, but that's not enjoyable.

**Additional context**
N/A

**Comment by Aga-C** [comment]
Can't you add emoji via your keyboard? It's a standard feature of soft keyboards (e.g. Gboard, SwiftKey, Simple Keyboard, AnySoftKeyboard).

**Comment by jahway603** [comment]
Closing. Had to change keyboard to Simple Keyboard and then have emoji. Did not work with OpenBoard keyboard.

**Comment by inson1** [comment]
@jahway603 openboard has emojis, wierd
